name: Python application
on:
  schedule:
    - cron: "0 1 * * *"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install python dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: make .env
        run: |
          touch .env
          echo "DISCORD_URL=${{ secrets.DISCORD_URL }}" >> .env

      - name: Run Crawling
        run: python main.py
